# Book settings
title: Genetic Basis of Mental Health
author: Shannon E. Ellis
logo: logo.svg

latex:
  latex_documents:
    targetname: book.tex

repository:
  url                       : https://github.com/shanellis/capstone-genetics-domain
  branch                    : master

launch_buttons:
  jupyterhub_url: "https://datahub.ucsd.edu"

html:
  favicon                   : "logo.svg"  # A path to a favicon image
  use_edit_page_button      : true  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : true  # Whether to add a link to your repository button
  use_issues_button         : true  # Whether to add an "open an issue" button